name: generate_21-069
on:
  schedule:
    - cron:  '5 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/mn:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate document
        run: |
          cd standard_template/standard
          metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc
          cp document.html ../../21-069.html
          cd ../../
          git config --global user.name 'opengeospatial'
          git config --global user.email 'opengeospatial@users.noreply.github.com'
          git add 21-069.html
          git commit -am "Automated generation of HTML documents"
          git push
